// Từ khoá nguyên liệu -> category (dùng để gom nhóm danh sách đi chợ)
const KEYWORD_MAP: Record<string, string[]> = {
  rau_cu: [
    "rau",
    "cải",
    "xà lách",
    "rau muống",
    "rau ngót",
    "rau dền",
    "mồng tơi",
    "bí",
    "cà chua",
    "cà rốt",
    "khoai tây",
    "khoai lang",
    "hành tây",
    "hành lá",
    "tỏi",
    "gừng",
    "nghệ",
    "ớt",
    "dưa chuột",
    "dưa leo",
    "su hào",
    "súp lơ",
    "bông cải",
    "bắp cải",
    "đậu cô ve",
    "đậu que",
    "giá đỗ",
    "nấm",
    "măng",
    "rau thơm",
    "ngò",
    "húng",
    "tía tô",
    "kinh giới",
    "đậu bắp",
    "ớt chuông",
  ],
  trai_cay: [
    "táo",
    "chuối",
    "cam",
    "quýt",
    "bưởi",
    "xoài",
    "dưa hấu",
    "nho",
    "lê",
    "kiwi",
    "dâu",
    "đu đủ",
    "thanh long",
    "vải",
    "nhãn",
    "mít",
    "sầu riêng",
    "chanh",
    "tắc",
    "ổi",
    "mận",
    "dừa",
    "trái cây",
  ],
  thit_ca_trung: [
    "thịt",
    "bò",
    "heo",
    "gà",
    "vịt",
    "cá",
    "tôm",
    "mực",
    "ngao",
    "sò",
    "cua",
    "ghẹ",
    "trứng",
    "xương",
    "ba chỉ",
    "sườn",
    "ức gà",
    "đùi gà",
    "cá hồi",
    "cá thu",
    "cá basa",
    "lươn",
    "chả",
    "giò",
    "xúc xích",
  ],
  sua_dam: [
    "sữa",
    "phô mai",
    "bơ",
    "kem",
    "yogurt",
    "sữa chua",
    "whey",
    "đậu phụ",
    "đậu hũ",
    "tàu hũ",
    "đậu nành",
    "sữa đậu",
  ],
  ngu_coc: [
    "gạo",
    "bún",
    "phở",
    "miến",
    "mì",
    "bánh phở",
    "bánh mì",
    "bánh tráng",
    "yến mạch",
    "ngũ cốc",
    "bột mì",
    "bột gạo",
    "bánh đa",
    "khoai",
    "ngô",
    "bắp",
    "đậu xanh",
    "đậu đỏ",
    "đậu đen",
    "hạt",
    "granola",
  ],
  gia_vi: [
    "muối",
    "đường",
    "tiêu",
    "nước mắm",
    "xì dầu",
    "tương",
    "dầu",
    "giấm",
    "bột ngọt",
    "hạt nêm",
    "mì chính",
    "tương ớt",
    "tương cà",
    "mayonnaise",
    "mật ong",
    "bột năng",
    "bột chiên",
    "rượu",
    "sa tế",
    "ngũ vị",
    "quế",
    "hồi",
  ],
};

export function categorizeIngredient(name?: string): string {
  if (!name) return "khac";
  const lower = name.toLowerCase();
  for (const [category, keywords] of Object.entries(KEYWORD_MAP)) {
    for (const kw of keywords) {
      if (lower.includes(kw)) {
        return category;
      }
    }
  }
  return "khac";
}
